application: clear-wind-782
version: 1
runtime: custom
vm: true
api_version: 1
threadsafe: true

#env_variables:
 # DBG_ENABLE: 'true'

# disable health-checking because this is so annoying during debugging
#vm_health_check:
  #enable_health_check: False
env_variables:
  DART_VM_OPTIONS: '--enable-async'