name: dartrest
dependencies:
  angular: 1.0.0
  appengine: '>=0.2.1 <0.3.0'
  browser: any
  forcemvc: '>=0.5.10 <0.6.0'
  http_server: '>=0.9.3 <0.10.0'
  logging: '>=0.9.0 <0.10.0'
  web_components: '>=0.9.0 <1.0.0'
dev_dependencies:
  mock: '>=0.11.0+2 <0.12.0'
  unittest: '>=0.11.0+5 <0.12.0'
transformers:
- angular:
    dart_sdk: /usr/lib/dart
    html_files:
    - lib/component/custom.html
