name: dartrest
dependencies:
  angular: "1.0.0"
  web_components: ">=0.8.0 <0.9.0"
  browser: ">=0.10.0+2 <0.11.0"
  appengine: '>=0.2.1 <0.3.0'
  forcemvc:
    git: https://github.com/ForceUniverse/dart-forcemvc
  http_server: '>=0.9.0 <0.10.0'
  logging: '>=0.9.0 <0.10.0'
dev_dependencies:
  unittest: ">=0.11.0+5 <0.12.0"
  mock: ">=0.11.0+2 <0.12.0"
transformers:
- angular:
    dart_sdk: "/usr/lib/dart"
    html_files:
      - web/lib/component/custom.html
